spring.application.name=projecthub

spring.datasource.url=jdbc:mysql://localhost:3306/projecthub
spring.datasource.username=root
spring.datasource.password=myx358rA
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.max-file-size=10MB

imgPath=D:/book/book-network/projecthub/backend/src/main/resources/static/img

filePath=D:/book/book-network/projecthub/backend/src/main/resources/static/uploads/files

max.file.size=104857600